name: Update README

on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          template: "templates/README.md.tpl"
          writeTo: "README.md"

      - name: Set timezone
        run: |
          ID="0e1ZjEuN-RXzAVO2A1KGAXr_g"
          URL=$(curl 'https://ckdatabasews.icloud.com/database/1/com.apple.cloudkit/production/public/records/resolve' \
            --data-raw "{\"shortGUIDs\":[{\"value\":\"$ID\"}]}" --compressed | jq -r '.results[0].rootRecord.fields.fileContent.value.downloadURL')
          TZ=$()
          sed -i "s/__TIMEZONE__/$(curl "$URL")/g" README.md

      - uses: actions/upload-artifact@v4
        with:
          name: README.md
          path: README.md

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update generated README
          branch: main
          commit_user_name: readme-scribe 🤖
          commit_user_email: actions@github.com
          commit_author: readme-scribe 🤖 <actions@github.com>
